trigger:
  - main  # change if your branch name is different

pool:
  name: Default   # IMPORTANT: use your self-hosted agent pool name

steps:
  # --- Build React frontend ---
  - script: |
      cd frontend
      npm install
      npm run build
    displayName: 'Build React App'

  # --- Build Node backend ---
  - script: |
      cd backend
      npm install
    displayName: 'Install Backend Dependencies'

  # --- Publish frontend build ---
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'frontend/build'
      ArtifactName: 'react-build'
    displayName: 'Publish React build artifact'

  # --- Publish backend ---
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'backend'
      ArtifactName: 'node-backend'
    displayName: 'Publish Node backend artifact'
